#! /bin/sh

IFS=$'\n'
for line in `w -hs`
do
	user=`echo $line | awk '{print $1}'`
	user_id=`id -u $user`
	disp_id=`echo $line | awk '{print $8}'`
	sudo -u $user DISPLAY=$disp_id DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/$user_id/bus \
		dunstify -u critical "SMARTD error ($SMARTD_FAILTYPE)" "$SMARTD_MESSAGE"
	echo "`date -I` $SMARTD_FAILTYPE: $SMARTD_MESSAGE" >> /root/smartd
done

