#! /usr/bin/fish 

set battery
set date
set wifi
set cpu
set memory
set temp
set vol
set light
set mpd
set idle

function getdate
	set date (date +'%A %d %B %Y, %H:%M')
end

function getbattery
	set acpib (acpi -b | cut -d "," -f 2 | sed -e "s/%//")
	set battery
	for bat in $acpib
		if test $bat -lt 25
			set battery "$battery $bat% "
		else if test $bat -lt 50
			set battery "$battery  "
		else if test $bat -lt 75
			set battery "$battery  "
		else
			set battery "$battery  "
		end
	end
end

function getwifi
	set wifi (awk 'NR==3 {print substr($3, 1, 2)}''' /proc/net/wireless)
	if test $wifi -lt 70
		set wifi " $wifi%  "
	else
		set wifi
	end
end

function getcpu
	set cpu (grep 'cpu ' /proc/stat | awk '{usage=($2+$4)*100/($2+$4+$5)} END {split(usage, a, "."); print a[1]}')
	if test $cpu -lt 75
		set cpu
	else
		set cpu " $cpu%  "
	end
end

function getmemory
	set memtotal (sed -n 's/MemTotal: *\(.*\) kB/\1/p' /proc/meminfo)
	set memavail (sed -n 's/MemAvailable: *\(.*\) kB/\1/p' /proc/meminfo)
	set memory (math "$memavail/$memtotal*100" | sed "s/\..*//")
	set memory (math 100-$memory)
	if test $memory -lt 75
		set memory
	else
		set memory " $memory%  "
	end
end

function gettemp
	set temp (cat /sys/class/thermal/thermal_zone2/temp | sed 's/...$//' )
	if test $temp -lt 40
		set temp " "
	else if test $temp -lt 55
		set temp " "
	else if test $temp -lt 70
		set temp " "
	else
		set temp "  $temp°C "
	end
end

function getvol
	set vol (amixer sget Master | awk '/%/ {gsub(/[\[%\]]/,""); print $4}')
	if test $vol = 0
		set vol "  "
	else if test $vol -lt 50
		set vol "  "
	else
		set vol "  "
		#  $vol%
	end
end

function getlight
	set light (math (brightnessctl g)/(brightnessctl m)\*100 | cut -d "." -f 1)
	if test $light -lt 100
		set light " $light% "
	else
		set light " "
	end
end

function getmpd
	set mpd (mpc current -f "%album% - %track%")
	set mpd "$mpd   "
end

function getidle
	if test (pidof swayidle)
		set idle
	else
		set idle " "
	end
end



function show
	#set screenlength (swaymsg -t get_outputs | sed -n -e "s/.*\"width\": \([^,]*\),/\1/p")
	#set -l infolength (echo "$wifi$cpu$memory$temp$vol$light$idle$mpd" | wc -m)
	#set -l spacelength "%"(math 165 - $infolength)"s"
	#echo "$battery$wifi$cpu$memory$temp$vol$light$idle$mpd"(printf "$spacelength" "")"$date "
	echo "$mpd$battery$wifi$cpu$memory$temp$vol$light$idle | $date "

	#echo "$wifi  $cpu  $memory  $temp  $vol  $light      $mpd                                    $date "
end


while true
	getbattery
	getdate
	show
	sleep 1

	getvol
	getlight
	getmpd
	show
	sleep 1

	getwifi
	getvol
	getlight
	getidle
	show
	sleep 1

	getcpu
	getvol
	getlight
	show
	sleep 1

	getmemory
	getvol
	getlight
	show
	sleep 1

	gettemp
	getvol
	getlight
	getidle
	show
	sleep 1

end

