#! /bin/sh
# normal, selected title filter hightlighted 
echo $XAPPS | sed 's/ /\n/g' | sort \
	| bemenu --fn liberation-mono 13 \
	-H 30 \
	--nb '#103c48' \
	--sb '#103c48' \
	--tb '#103c48' \
	--fb '#103c48' \
	--hb '#103c48' \
	--nf '#adbcbc' \
	--tf '#adbcbc' \
	--ff '#adbcbc' \
	--sf '#adbcbc' \
	--hf '#75b938' \
	-p '>' \
	wayland | xargs sh -c
